server:
  port: 5680
  servlet:
    context-path: /dataadmin

spring:
  application:
    name: dataround-admin

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dataround_admin?currentSchema=public
    username: postgres
    password: "dataround.io"
  sql:
    init:
      data-locations: classpath:postgresql-schema.sql
      # mode: always - execute script on every startup
      mode: always

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

dataround:
  login:
    interceptor:
      escape: "/api/login, /api/logout, /api/captcha, /error, /static/**, /**/*.css, /**/*.js, /**/*.html, /**/*.png, /**/*.jpg, /**/*.gif, /**/*.svg, /**/*.woff, /**/*.woff2, /**/*.ttf, /**/*.ico"

# Logger Config
logging:
  level:
    io.dataround: debug